lst = [10, 20, "Payel", -10, 30, 5]
print(lst)
print(lst[2])
print(lst[3:5])
print(lst*4)
print(len(lst))
lst.remove("Payel")
print(lst)
del (lst[1])
print(lst)
lst.append(40)
print(lst)
#lst.clear()
#print(lst)
print(max(lst))
print(min(lst))
lst.insert(3, 100)
print(lst)
#lst.sort()
#print(lst)
lst.sort(reverse=True)
print(lst)

list1 = ["Payel" , 1, 5, 10]
print(list1)
list1.remove("1")
print(list1)
del(list1[1])
print(list1)
list1.insert(3, 100)
print(list1)